#!C:\Users\v4qu1\Documents\Freelancer\ATS Project\ATS\ats_project\Scripts\python.exe

import docx2txt

if __name__ == '__main__':
    import sys
    args = docx2txt.process_args()
    text = docx2txt.process(args.docx, args.img_dir)
    output = getattr(sys.stdout, 'buffer', sys.stdout)
    output.write(text.encode('utf-8'))
